name: "Notarize Action"
description: "Apple notarizes your stuffs"
branding:
  icon: zap
  color: purple

inputs:
  product-path:
    description: "The path to the product to notarize."
    required: true
  appstore-connect-username:
    description: "The AppStore Connect username."
    required: true
  appstore-connect-password:
    description: "The AppStore Connect password."
    required: true
  appstore-connect-team-id:
    description: "The Apple Developer account Team ID. Only required when using notarytool."
    required: true

  appstore-connect-api-key:
    description: "The AppStore Connect API Key."
    required: false
  appstore-connect-api-issuer:
    description: "The AppStore Connect API Issuer."
    required: false
  primary-bundle-id:
    description: "A unique identifier that identifies this product notarization. Defaults to the bundle identifier of the app you are uploading."
    required: false
  tool:
    description: "The xcrun notarization tool to use."
    required: false
    default: notarytool
  verbose:
    description: "Verbose mode will print Notarization API responses."
    required: false
    default: false

outputs:
  product-path:
    description: "The path to the product that was notarized"

runs:
  using: "node18"
  main: "dist/index.js"
